/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as FoodsIndexRouteImport } from './routes/foods.index'
import { Route as FoodsCodeRouteImport } from './routes/foods.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsIndexRoute = FoodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FoodsRoute,
} as any)
const FoodsCodeRoute = FoodsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => FoodsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/foods': typeof FoodsRouteWithChildren
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/foods/$code': typeof FoodsCodeRoute
  '/foods/': typeof FoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/foods/$code': typeof FoodsCodeRoute
  '/foods': typeof FoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/contact': typeof ContactRoute
  '/foods': typeof FoodsRouteWithChildren
  '/learn': typeof LearnRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/foods/$code': typeof FoodsCodeRoute
  '/foods/': typeof FoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/foods'
    | '/learn'
    | '/privacy'
    | '/terms'
    | '/foods/$code'
    | '/foods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/learn'
    | '/privacy'
    | '/terms'
    | '/foods/$code'
    | '/foods'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/contact'
    | '/foods'
    | '/learn'
    | '/privacy'
    | '/terms'
    | '/foods/$code'
    | '/foods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  ContactRoute: typeof ContactRoute
  FoodsRoute: typeof FoodsRouteWithChildren
  LearnRoute: typeof LearnRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/': {
      id: '/foods/'
      path: '/'
      fullPath: '/foods/'
      preLoaderRoute: typeof FoodsIndexRouteImport
      parentRoute: typeof FoodsRoute
    }
    '/foods/$code': {
      id: '/foods/$code'
      path: '/$code'
      fullPath: '/foods/$code'
      preLoaderRoute: typeof FoodsCodeRouteImport
      parentRoute: typeof FoodsRoute
    }
  }
}

interface FoodsRouteChildren {
  FoodsCodeRoute: typeof FoodsCodeRoute
  FoodsIndexRoute: typeof FoodsIndexRoute
}

const FoodsRouteChildren: FoodsRouteChildren = {
  FoodsCodeRoute: FoodsCodeRoute,
  FoodsIndexRoute: FoodsIndexRoute,
}

const FoodsRouteWithChildren = FoodsRoute._addFileChildren(FoodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  ContactRoute: ContactRoute,
  FoodsRoute: FoodsRouteWithChildren,
  LearnRoute: LearnRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
