// AUTO-GENERATED by scripts/gen_foods.py — do not edit by hand.
// Kept separate from foodsKfct.ts so pages that only show the count
// don't pull the whole dataset into their bundle.

export const KFCT_FOOD_COUNT = 656;
