// AUTO-GENERATED by scripts/gen_data.py — do not edit by hand.
// Nutrition: Kenya Food Composition Tables 2018 (per 100 g).
// Prices: WFP Global Food Prices (Kenya), retail, latest per market, median by region.

export const PRICE_REGIONS = ["Coast", "Eastern", "Nairobi", "North Eastern", "Rift Valley"] as const;
export type Region = (typeof PRICE_REGIONS)[number];

export const REGION_PRICE_DATE: Record<string, string> = {
 "Coast": "2026-03-15",
 "Eastern": "2026-03-15",
 "Nairobi": "2022-01-15",
 "North Eastern": "2026-05-15",
 "Rift Valley": "2026-04-15"
};

// Median retail KES per kg, by region then commodity.
export const REGIONAL_PRICE_PER_KG: Record<string, Record<string, number>> = {
 "Coast": {
  "Maize (white)": 37.6,
  "Beans (dry)": 106.25,
  "Maize flour (white)": 81.0,
  "Rice (aromatic)": 116.5,
  "Wheat flour": 91.5,
  "Salt": 71.25,
  "Sugar": 155.0,
  "Beans": 140.0,
  "Cowpeas (dry)": 150.0,
  "Kale": 78.0,
  "Spinach": 87.0,
  "Maize (white, dry)": 70.0,
  "Pigeon peas (dry)": 150.0,
  "Maize flour": 58.12,
  "Potatoes (Irish)": 50.0,
  "Rice": 98.75,
  "Cooking fat": 220.0,
  "Meat (beef)": 500.0,
  "Meat (goat)": 511.66,
  "Maize": 52.91,
  "Sorghum": 65.0,
  "Meat (camel)": 530.0
 },
 "Eastern": {
  "Maize (white)": 40.0,
  "Beans (dry)": 120.0,
  "Maize (white, dry)": 64.0,
  "Maize flour (white)": 99.5,
  "Rice (aromatic)": 122.0,
  "Wheat flour": 100.0,
  "Salt": 75.0,
  "Sugar": 159.0,
  "Kale": 67.0,
  "Spinach": 88.0,
  "Beans": 130.0,
  "Cowpeas (dry)": 150.0,
  "Pigeon peas (dry)": 156.0,
  "Maize": 55.0,
  "Maize flour": 66.66,
  "Potatoes (Irish)": 92.5,
  "Rice": 119.16,
  "Sorghum": 50.0,
  "Meat (beef)": 500.0,
  "Meat (camel)": 450.0,
  "Cooking fat": 281.66
 },
 "Nairobi": {
  "Bread": 112.5,
  "Maize": 50.0,
  "Maize flour": 58.75,
  "Potatoes (Irish)": 59.38,
  "Rice": 100.0,
  "Sorghum": 80.0,
  "Wheat flour": 68.12,
  "Meat (beef)": 550.0,
  "Meat (goat)": 533.33,
  "Sugar": 117.5,
  "Cooking fat": 156.9,
  "Onions (red)": 57.0,
  "Tomatoes": 58.0,
  "Salt": 50.0,
  "Beans (dry)": 119.0,
  "Meat (camel)": 450.0
 },
 "North Eastern": {
  "Maize (white)": 76.0,
  "Maize (white, dry)": 90.0,
  "Maize flour (white)": 100.0,
  "Beans": 145.0,
  "Kale": 94.0,
  "Rice (aromatic)": 140.0,
  "Wheat flour": 100.0,
  "Salt": 100.0,
  "Sugar": 132.0,
  "Spinach": 81.5,
  "Cowpeas (dry)": 148.5,
  "Pigeon peas (dry)": 263.0,
  "Maize flour": 98.75,
  "Potatoes (Irish)": 80.5,
  "Rice": 117.19,
  "Beans (dry)": 123.17,
  "Sorghum": 100.0,
  "Maize": 60.0,
  "Meat (camel)": 615.0,
  "Meat (goat)": 800.0,
  "Cooking fat": 198.33,
  "Meat (beef)": 10.0
 },
 "Rift Valley": {
  "Maize (white)": 55.0,
  "Beans (dry)": 120.0,
  "Maize (white, dry)": 71.5,
  "Maize flour (white)": 87.0,
  "Rice (aromatic)": 123.0,
  "Wheat flour": 100.0,
  "Salt": 75.0,
  "Sugar": 160.0,
  "Beans": 139.0,
  "Kale": 70.0,
  "Spinach": 77.0,
  "Cowpeas (dry)": 150.0,
  "Pigeon peas (dry)": 172.5,
  "Maize": 60.0,
  "Maize flour": 80.0,
  "Potatoes (Irish)": 100.0,
  "Rice": 133.33,
  "Meat (beef)": 700.0,
  "Meat (goat)": 700.0,
  "Sorghum": 80.0,
  "Meat (camel)": 766.67,
  "Cooking fat": 215.0
 }
};

// Monthly seasonality: % vs annual median for each WFP commodity (null = no data that month).
export interface SeasonalIndex { index: Array<number | null>; monthsCovered: number; }
export const SEASONAL_INDEX: Record<string, SeasonalIndex> = {
 "Beans (dry)": {
  "index": [
   0,
   8,
   -16,
   1,
   4,
   null,
   48,
   -24,
   null,
   null,
   -10,
   -10
  ],
  "monthsCovered": 9
 },
 "Maize": {
  "index": [
   -12,
   -12,
   -12,
   6,
   6,
   null,
   -29,
   -8,
   null,
   null,
   -6,
   null
  ],
  "monthsCovered": 8
 },
 "Sorghum": {
  "index": [
   0,
   20,
   -8,
   -12,
   25,
   25,
   -38,
   5,
   0,
   -25,
   -6,
   null
  ],
  "monthsCovered": 11
 },
 "Wheat flour": {
  "index": [
   -33,
   -22,
   -2,
   -13,
   -4,
   12,
   null,
   -40,
   8,
   null,
   -27,
   6
  ],
  "monthsCovered": 10
 },
 "Sugar": {
  "index": [
   -24,
   -24,
   0,
   0,
   -23,
   1,
   null,
   -32,
   0,
   null,
   -20,
   2
  ],
  "monthsCovered": 10
 },
 "Cooking fat": {
  "index": [
   -3,
   1,
   -34,
   null,
   -3,
   6,
   -3,
   -15,
   null,
   null,
   6,
   -3
  ],
  "monthsCovered": 9
 },
 "Salt": {
  "index": [
   -31,
   -31,
   3,
   -2,
   -22,
   -17,
   null,
   -31,
   -17,
   null,
   -31,
   3
  ],
  "monthsCovered": 10
 }
};

export const NATIONAL_PRICE_PER_KG: Record<string, number> = {
 "Maize (white)": 51.0,
 "Beans (dry)": 120.0,
 "Bread": 112.5,
 "Maize": 60.0,
 "Maize flour": 81.66,
 "Potatoes (Irish)": 98.34,
 "Rice": 120.38,
 "Sorghum": 80.0,
 "Wheat flour": 100.0,
 "Meat (beef)": 700.0,
 "Meat (goat)": 700.0,
 "Sugar": 156.0,
 "Cooking fat": 207.0,
 "Onions (red)": 57.0,
 "Tomatoes": 58.0,
 "Maize flour (white)": 95.0,
 "Rice (aromatic)": 123.0,
 "Salt": 77.5,
 "Beans": 140.0,
 "Cowpeas (dry)": 150.0,
 "Kale": 80.0,
 "Spinach": 80.0,
 "Maize (white, dry)": 74.0,
 "Pigeon peas (dry)": 160.0,
 "Meat (camel)": 689.21
};

// Mkulima Bora urban-retail: per-portion KES by food code (real, dated). Ranked above WFP.
export const MKULIMA_DATE = "2026-07-19";
export const MKULIMA_PORTION_KES: Record<string, number> = {
 "04039": 7,
 "08002": 28,
 "03019": 22,
 "05003": 12
};

export interface GenFood {
  code: string;
  name: string;
  group: string;
  portionLabel: string;
  portionGrams: number;
  wfpCommodity: string | null;
  priceGrams: number | null;
  estPriceKES: number;
  kcal: number | null;
  protein: number | null;
  fat: number | null;
  carbs: number | null;
  fibre: number | null;
  iron: number | null;
  calcium: number | null;
  zinc: number | null;
  sodium: number | null;
  vitA: number | null;
  vitC: number | null;
}

export const GEN_FOODS: GenFood[] = [
  { code: "15005", name: "Ugali (maize)", group: "Cereals", portionLabel: "1 slab (250g)", portionGrams: 250, wfpCommodity: "Maize flour", priceGrams: 100, estPriceKES: 25, kcal: 141.0, protein: 3.3, fat: 1.8, carbs: 26.0, fibre: 3.8, iron: 1.1, calcium: 12.0, zinc: 0.77, sodium: 7.0, vitA: 0.0, vitC: 0.0 },
  { code: "15053", name: "Githeri (maize + beans)", group: "Mixed dishes", portionLabel: "1 plate (300g)", portionGrams: 300, wfpCommodity: null, priceGrams: null, estPriceKES: 45, kcal: 157.0, protein: 6.7, fat: 4.2, carbs: 19.7, fibre: 7.2, iron: 2.2, calcium: 39.0, zinc: 1.01, sodium: 233.0, vitA: null, vitC: 0.5 },
  { code: "15054", name: "Mukimo", group: "Mixed dishes", portionLabel: "1 plate (300g)", portionGrams: 300, wfpCommodity: null, priceGrams: null, estPriceKES: 60, kcal: 118.0, protein: 5.0, fat: 0.7, carbs: 20.5, fibre: 4.8, iron: 2.0, calcium: 38.0, zinc: 0.74, sodium: 266.0, vitA: null, vitC: 2.7 },
  { code: "15056", name: "Matoke (banana + meat)", group: "Mixed dishes", portionLabel: "1 plate (300g)", portionGrams: 300, wfpCommodity: null, priceGrams: null, estPriceKES: 70, kcal: 118.0, protein: 6.0, fat: 4.1, carbs: 13.3, fibre: 1.8, iron: 3.9, calcium: 16.0, zinc: 1.12, sodium: 381.0, vitA: null, vitC: 9.8 },
  { code: "01034", name: "Rice, white", group: "Cereals", portionLabel: "1 plate (~70g dry)", portionGrams: 70, wfpCommodity: "Rice", priceGrams: 70, estPriceKES: 35, kcal: 353.0, protein: 7.6, fat: 1.0, carbs: 78.1, fibre: 0.7, iron: 0.9, calcium: 21.0, zinc: 1.32, sodium: 17.0, vitA: 0.0, vitC: 0.0 },
  { code: "01039", name: "Sorghum ugali", group: "Cereals", portionLabel: "1 plate (~80g dry)", portionGrams: 80, wfpCommodity: "Sorghum", priceGrams: 80, estPriceKES: 30, kcal: 341.0, protein: 10.8, fat: 3.5, carbs: 60.5, fibre: 11.9, iron: 6.4, calcium: 18.0, zinc: 1.69, sodium: 6.0, vitA: 1.0, vitC: 0.0 },
  { code: "15019", name: "Chapati", group: "Cereals", portionLabel: "1 piece (60g)", portionGrams: 60, wfpCommodity: "Wheat flour", priceGrams: 45, estPriceKES: 20, kcal: 424.0, protein: 7.8, fat: 21.1, carbs: 49.6, fibre: 2.5, iron: 3.9, calcium: 25.0, zinc: 0.61, sodium: 100.0, vitA: 59.0, vitC: 0.0 },
  { code: "01007", name: "White bread", group: "Cereals", portionLabel: "2 slices (60g)", portionGrams: 60, wfpCommodity: "Bread", priceGrams: 60, estPriceKES: 15, kcal: 249.0, protein: 7.7, fat: 1.9, carbs: 48.8, fibre: 3.1, iron: 1.7, calcium: null, zinc: 0.8, sodium: 466.0, vitA: null, vitC: 0.0 },
  { code: "02009", name: "Potato, boiled", group: "Vegetables", portionLabel: "1 plate (200g)", portionGrams: 200, wfpCommodity: "Potatoes (Irish)", priceGrams: 220, estPriceKES: 30, kcal: 105.0, protein: 2.4, fat: 0.1, carbs: 22.7, fibre: 1.68, iron: 1.4, calcium: 9.0, zinc: 0.32, sodium: 6.46, vitA: null, vitC: 6.6 },
  { code: "02014", name: "Sweet potato, orange", group: "Cereals", portionLabel: "1 medium (180g)", portionGrams: 180, wfpCommodity: null, priceGrams: null, estPriceKES: 30, kcal: 76.9, protein: 1.9, fat: 0.1, carbs: 15.6, fibre: 3.0, iron: 0.5, calcium: 27.0, zinc: 0.5, sodium: 10.0, vitA: null, vitC: 31.0 },
  { code: "02023", name: "Cassava, boiled", group: "Cereals", portionLabel: "1 piece (150g)", portionGrams: 150, wfpCommodity: null, priceGrams: null, estPriceKES: 25, kcal: 148.0, protein: 1.1, fat: 0.2, carbs: 33.4, fibre: 3.9, iron: 0.7, calcium: 27.0, zinc: 0.26, sodium: 1.0, vitA: null, vitC: 23.0 },
  { code: "02020", name: "Arrowroot (nduma)", group: "Cereals", portionLabel: "1 piece (150g)", portionGrams: 150, wfpCommodity: null, priceGrams: null, estPriceKES: 50, kcal: 109.0, protein: 3.2, fat: 0.3, carbs: 22.3, fibre: 2.0, iron: 1.0, calcium: 6.0, zinc: 0.86, sodium: 28.0, vitA: 1.0, vitC: 1.0 },
  { code: "03004", name: "Beans, boiled", group: "Legumes", portionLabel: "1 plate (~90g dry)", portionGrams: 90, wfpCommodity: "Beans (dry)", priceGrams: 90, estPriceKES: 40, kcal: 305.0, protein: 20.5, fat: 2.0, carbs: 40.6, fibre: 21.2, iron: 6.4, calcium: 106.0, zinc: 2.78, sodium: 22.0, vitA: 1.0, vitC: 0.3 },
  { code: "15114", name: "Njahi (black bean) stew", group: "Legumes", portionLabel: "1 plate (250g)", portionGrams: 250, wfpCommodity: null, priceGrams: null, estPriceKES: 55, kcal: 62.0, protein: 3.6, fat: 1.3, carbs: 7.7, fibre: 2.8, iron: 1.2, calcium: 17.0, zinc: 0.42, sodium: 164.0, vitA: 3.0, vitC: 2.6 },
  { code: "03019", name: "Ndengu (green gram)", group: "Legumes", portionLabel: "1 plate (~80g dry)", portionGrams: 80, wfpCommodity: null, priceGrams: null, estPriceKES: 45, kcal: 311.0, protein: 27.2, fat: 1.7, carbs: 38.4, fibre: 16.7, iron: 7.6, calcium: 151.0, zinc: 2.62, sodium: 26.0, vitA: 9.0, vitC: 3.0 },
  { code: "04020", name: "Sukuma wiki (kale)", group: "Vegetables", portionLabel: "1 serving (150g)", portionGrams: 150, wfpCommodity: "Kale", priceGrams: 200, estPriceKES: 20, kcal: 29.0, protein: 3.0, fat: 0.3, carbs: 1.2, fibre: 4.7, iron: 2.8, calcium: 402.0, zinc: 0.5, sodium: 71.0, vitA: 177.0, vitC: 134.0 },
  { code: "04030", name: "Spinach", group: "Vegetables", portionLabel: "1 serving (120g)", portionGrams: 120, wfpCommodity: "Spinach", priceGrams: 150, estPriceKES: 25, kcal: 27.0, protein: 2.8, fat: 0.4, carbs: 1.1, fibre: 4.1, iron: 1.7, calcium: 131.0, zinc: 1.0, sodium: 59.0, vitA: null, vitC: 37.0 },
  { code: "04039", name: "Terere (amaranth leaves)", group: "Indigenous vegetables", portionLabel: "1 serving (120g)", portionGrams: 120, wfpCommodity: null, priceGrams: null, estPriceKES: 20, kcal: 38.0, protein: 3.9, fat: 0.3, carbs: 1.3, fibre: 7.6, iron: 5.3, calcium: 280.0, zinc: 0.73, sodium: 14.0, vitA: 309.0, vitC: 33.0 },
  { code: "04003", name: "Managu (nightshade)", group: "Indigenous vegetables", portionLabel: "1 serving (120g)", portionGrams: 120, wfpCommodity: null, priceGrams: null, estPriceKES: 25, kcal: 31.0, protein: 3.8, fat: 0.1, carbs: 1.3, fibre: 4.3, iron: 8.6, calcium: 100.0, zinc: 0.65, sodium: 10.0, vitA: 2.0, vitC: 36.0 },
  { code: "04070", name: "Mrenda (jute mallow)", group: "Indigenous vegetables", portionLabel: "1 serving (120g)", portionGrams: 120, wfpCommodity: null, priceGrams: null, estPriceKES: 25, kcal: 47.0, protein: 4.9, fat: 0.2, carbs: 2.2, fibre: 8.7, iron: 5.0, calcium: 207.0, zinc: 0.46, sodium: 14.0, vitA: 205.0, vitC: 18.3 },
  { code: "04066", name: "Kunde (cowpea leaves)", group: "Indigenous vegetables", portionLabel: "1 serving (120g)", portionGrams: 120, wfpCommodity: null, priceGrams: null, estPriceKES: 20, kcal: 28.0, protein: 3.2, fat: 0.4, carbs: 0.6, fibre: 4.7, iron: 1.9, calcium: 170.0, zinc: 0.53, sodium: 22.0, vitA: 0.0, vitC: 19.0 },
  { code: "04036", name: "Tomato", group: "Vegetables", portionLabel: "2 medium (150g)", portionGrams: 150, wfpCommodity: "Tomatoes", priceGrams: 150, estPriceKES: 20, kcal: 22.0, protein: 1.0, fat: 0.2, carbs: 3.3, fibre: 1.4, iron: 0.9, calcium: 8.0, zinc: 0.37, sodium: 21.0, vitA: null, vitC: 25.0 },
  { code: "13023", name: "Onion, red", group: "Vegetables", portionLabel: "1 medium (60g)", portionGrams: 60, wfpCommodity: "Onions (red)", priceGrams: 60, estPriceKES: 10, kcal: 42.0, protein: 1.5, fat: 0.1, carbs: 7.6, fibre: 2.3, iron: 0.9, calcium: null, zinc: 0.16, sodium: 5.0, vitA: null, vitC: 7.0 },
  { code: "08002", name: "Omena (silver fish)", group: "Fish", portionLabel: "1 mug (60g)", portionGrams: 60, wfpCommodity: null, priceGrams: null, estPriceKES: 50, kcal: 333.0, protein: 59.5, fat: 10.6, carbs: 0.0, fibre: 0.0, iron: 6.9, calcium: 2790.0, zinc: 16.0, sodium: 300.0, vitA: null, vitC: null },
  { code: "08010", name: "Tilapia", group: "Fish", portionLabel: "1 fillet (120g)", portionGrams: 120, wfpCommodity: null, priceGrams: null, estPriceKES: 90, kcal: 92.0, protein: 19.7, fat: 1.5, carbs: 0.0, fibre: 0.0, iron: 2.7, calcium: 109.0, zinc: 0.5, sodium: 64.0, vitA: null, vitC: null },
  { code: "07002", name: "Beef, lean", group: "Meat", portionLabel: "1 portion (120g)", portionGrams: 120, wfpCommodity: "Meat (beef)", priceGrams: 120, estPriceKES: 90, kcal: 104.0, protein: 20.6, fat: 2.3, carbs: 0.4, fibre: 0.0, iron: 2.3, calcium: 5.0, zinc: 4.22, sodium: 107.0, vitA: null, vitC: 0.5 },
  { code: "07011", name: "Egg, whole", group: "Dairy", portionLabel: "1 egg (55g)", portionGrams: 55, wfpCommodity: null, priceGrams: null, estPriceKES: 20, kcal: 134.0, protein: 12.7, fat: 8.1, carbs: 2.4, fibre: 0.0, iron: 1.7, calcium: 54.0, zinc: 1.13, sodium: 155.0, vitA: null, vitC: 0.0 },
  { code: "06022", name: "Milk, cow, fresh", group: "Dairy", portionLabel: "1 cup (250ml)", portionGrams: 250, wfpCommodity: null, priceGrams: null, estPriceKES: 30, kcal: 70.0, protein: 3.3, fat: 3.5, carbs: 6.1, fibre: 0.0, iron: 0.1, calcium: 119.0, zinc: 0.63, sodium: 39.0, vitA: null, vitC: 0.0 },
  { code: "05003", name: "Avocado", group: "Fruits", portionLabel: "1 medium (150g)", portionGrams: 150, wfpCommodity: null, priceGrams: null, estPriceKES: 20, kcal: 185.0, protein: 1.6, fat: 19.6, carbs: 0.0, fibre: 4.0, iron: 1.0, calcium: 19.0, zinc: 0.39, sodium: 7.0, vitA: null, vitC: 14.0 },
  { code: "05004", name: "Banana", group: "Fruits", portionLabel: "1 piece (120g)", portionGrams: 120, wfpCommodity: null, priceGrams: null, estPriceKES: 15, kcal: 95.0, protein: 1.08, fat: 0.3, carbs: 20.6, fibre: 2.75, iron: 0.3, calcium: 10.0, zinc: 0.36, sodium: 0.0, vitA: null, vitC: 4.0 },
  { code: "05023", name: "Orange", group: "Fruits", portionLabel: "1 piece (130g)", portionGrams: 130, wfpCommodity: null, priceGrams: null, estPriceKES: 20, kcal: 42.0, protein: 0.9, fat: 0.2, carbs: 7.5, fibre: 3.1, iron: 0.2, calcium: 23.0, zinc: 0.05, sodium: 5.0, vitA: null, vitC: 45.0 },
  { code: "05019", name: "Mango", group: "Fruits", portionLabel: "1 medium (200g)", portionGrams: 200, wfpCommodity: null, priceGrams: null, estPriceKES: 30, kcal: 64.0, protein: 0.6, fat: 0.3, carbs: 14.0, fibre: 1.6, iron: 0.2, calcium: 14.0, zinc: 0.14, sodium: 1.0, vitA: null, vitC: 35.0 },
  { code: "05024", name: "Papaya (pawpaw)", group: "Fruits", portionLabel: "1 slice (150g)", portionGrams: 150, wfpCommodity: null, priceGrams: null, estPriceKES: 20, kcal: 36.0, protein: 0.6, fat: 0.3, carbs: 6.8, fibre: 2.1, iron: 0.6, calcium: 21.0, zinc: 0.2, sodium: 4.0, vitA: null, vitC: 51.0 },
];
